name: Build

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Detect target version
        run: |
          event_name=${{ github.event_name }}
          echo "Event name: $event_name"
          target_version=$([ $event_name = workflow_dispatch ] && echo -n latest || echo -n beta)
          echo "Target version: $target_version"
          echo "TARGET_VERSION=$target_version" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Apify CLI
        run: |
          npm install -g apify-cli
          apify login --token ${{ secrets.APIFY_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create empty directory for build context
        run: |
          mkdir -p base-build
          cp base.Dockerfile base-build/Dockerfile

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v4
        with:
          context: base-build
          push: true
          tags: ghcr.io/mvolfik/argos-translator-base:${{ env.TARGET_VERSION }}
          cache-from: type=gha
          cache-to: type=gha

      - name: Build runner actors
        run: ./buildRunnerActors.sh
        env:
          BASE_IMAGE_DIGEST: ${{ steps.docker-build.outputs.digest }}
